version: '3'

services:
  samba:
    tty: true
    network_mode: bridge
    volumes:
      - /Users/landy/Downloads/apks/:/Shared
      - /Users/landy/workspace/github/docker-smb/smb.conf:/etc/samba/smb.conf
    ports:
      - "139:139"
      - "445:445"
    build:
      context: .
      dockerfile: Dockerfile
